// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: alerta.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TipoAlerta int32

const (
	TipoAlerta_DESCONOCIDO     TipoAlerta = 0
	TipoAlerta_SALUD           TipoAlerta = 1
	TipoAlerta_ALIMENTOS       TipoAlerta = 2
	TipoAlerta_SEGURIDAD       TipoAlerta = 3
	TipoAlerta_INFRAESTRUCTURA TipoAlerta = 4
)

// Enum value maps for TipoAlerta.
var (
	TipoAlerta_name = map[int32]string{
		0: "DESCONOCIDO",
		1: "SALUD",
		2: "ALIMENTOS",
		3: "SEGURIDAD",
		4: "INFRAESTRUCTURA",
	}
	TipoAlerta_value = map[string]int32{
		"DESCONOCIDO":     0,
		"SALUD":           1,
		"ALIMENTOS":       2,
		"SEGURIDAD":       3,
		"INFRAESTRUCTURA": 4,
	}
)

func (x TipoAlerta) Enum() *TipoAlerta {
	p := new(TipoAlerta)
	*p = x
	return p
}

func (x TipoAlerta) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TipoAlerta) Descriptor() protoreflect.EnumDescriptor {
	return file_alerta_proto_enumTypes[0].Descriptor()
}

func (TipoAlerta) Type() protoreflect.EnumType {
	return &file_alerta_proto_enumTypes[0]
}

func (x TipoAlerta) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TipoAlerta.Descriptor instead.
func (TipoAlerta) EnumDescriptor() ([]byte, []int) {
	return file_alerta_proto_rawDescGZIP(), []int{0}
}

type Reporte struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo          TipoAlerta             `protobuf:"varint,2,opt,name=tipo,proto3,enum=alerta.TipoAlerta" json:"tipo,omitempty"`
	Lat           float32                `protobuf:"fixed32,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float32                `protobuf:"fixed32,4,opt,name=lng,proto3" json:"lng,omitempty"`
	Mensaje       string                 `protobuf:"bytes,5,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReporteroId   string                 `protobuf:"bytes,7,opt,name=reportero_id,json=reporteroId,proto3" json:"reportero_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reporte) Reset() {
	*x = Reporte{}
	mi := &file_alerta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reporte) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reporte) ProtoMessage() {}

func (x *Reporte) ProtoReflect() protoreflect.Message {
	mi := &file_alerta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reporte.ProtoReflect.Descriptor instead.
func (*Reporte) Descriptor() ([]byte, []int) {
	return file_alerta_proto_rawDescGZIP(), []int{0}
}

func (x *Reporte) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reporte) GetTipo() TipoAlerta {
	if x != nil {
		return x.Tipo
	}
	return TipoAlerta_DESCONOCIDO
}

func (x *Reporte) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Reporte) GetLng() float32 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Reporte) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *Reporte) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Reporte) GetReporteroId() string {
	if x != nil {
		return x.ReporteroId
	}
	return ""
}

var File_alerta_proto protoreflect.FileDescriptor

const file_alerta_proto_rawDesc = "" +
	"\n" +
	"\falerta.proto\x12\x06alerta\"\xc0\x01\n" +
	"\aReporte\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04tipo\x18\x02 \x01(\x0e2\x12.alerta.TipoAlertaR\x04tipo\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lng\x18\x04 \x01(\x02R\x03lng\x12\x18\n" +
	"\amensaje\x18\x05 \x01(\tR\amensaje\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12!\n" +
	"\freportero_id\x18\a \x01(\tR\vreporteroId*[\n" +
	"\n" +
	"TipoAlerta\x12\x0f\n" +
	"\vDESCONOCIDO\x10\x00\x12\t\n" +
	"\x05SALUD\x10\x01\x12\r\n" +
	"\tALIMENTOS\x10\x02\x12\r\n" +
	"\tSEGURIDAD\x10\x03\x12\x13\n" +
	"\x0fINFRAESTRUCTURA\x10\x04B\x06Z\x04./pbb\x06proto3"

var (
	file_alerta_proto_rawDescOnce sync.Once
	file_alerta_proto_rawDescData []byte
)

func file_alerta_proto_rawDescGZIP() []byte {
	file_alerta_proto_rawDescOnce.Do(func() {
		file_alerta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alerta_proto_rawDesc), len(file_alerta_proto_rawDesc)))
	})
	return file_alerta_proto_rawDescData
}

var file_alerta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_alerta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alerta_proto_goTypes = []any{
	(TipoAlerta)(0), // 0: alerta.TipoAlerta
	(*Reporte)(nil), // 1: alerta.Reporte
}
var file_alerta_proto_depIdxs = []int32{
	0, // 0: alerta.Reporte.tipo:type_name -> alerta.TipoAlerta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_alerta_proto_init() }
func file_alerta_proto_init() {
	if File_alerta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alerta_proto_rawDesc), len(file_alerta_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alerta_proto_goTypes,
		DependencyIndexes: file_alerta_proto_depIdxs,
		EnumInfos:         file_alerta_proto_enumTypes,
		MessageInfos:      file_alerta_proto_msgTypes,
	}.Build()
	File_alerta_proto = out.File
	file_alerta_proto_goTypes = nil
	file_alerta_proto_depIdxs = nil
}
